[workspace]
members = [
    "colorchange",
    "colorchangesimple",
    "colorkey",
    "createalpha",
    "libs",
    "opticaldiffusion",
    "pixelselector",
]

[patch.crates-io.win_dbg_logger]
git = "https://github.com/wladwm/win_dbg_logger"
branch = "master"
