[workspace]
members = [
  "pixelselector",
  "libs",
  "colorchange",
  "colorchangesimple",
  "colorkey",
  "createalpha",
]

[patch.crates-io]
win_dbg_logger = { git = "https://github.com/wladwm/win_dbg_logger", branch = "master" }
